# Generated by Django 3.2.6 on 2021-09-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenttypes',
            old_name='short_name',
            new_name='type_name',
        ),
    ]
