# Generated by Django 3.2.6 on 2021-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
