# Generated by Django 3.2.6 on 2021-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstationcontent',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstationcontent',
            name='charger_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstationcontent',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contenttypes',
            name='class_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contenttypes',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gasfillingstationcontent',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gasfillingstationcontent',
            name='lng_cng',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gasfillingstationcontent',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gasfillingstationcontent',
            name='operator',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
