# Generated by Django 3.2.6 on 2021-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0003_unitgroup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitgroup',
            name='description',
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
