# Generated by Django 3.2.6 on 2021-10-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0006_unitgroup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
