# Generated by Django 3.2.6 on 2021-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0007_remove_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuecontent',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='walkingroutecontent',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
