# Generated by Django 3.2.6 on 2021-10-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0008_auto_20211004_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstationcontent',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gasfillingstationcontent',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
