# Generated by Django 3.2.6 on 2021-10-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0009_auto_20211004_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_fi',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unitgroup',
            name='name_sv',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
