# Generated by Django 3.2.6 on 2021-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0010_auto_20211004_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
