# Generated by Django 3.2.6 on 2021-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0011_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_fi',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_sv',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
