# Generated by Django 3.2.6 on 2021-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0012_auto_20211004_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
