# Generated by Django 3.2.6 on 2021-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0013_unit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstationcontent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='gasfillingstationcontent',
            name='address',
        ),
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
