# Generated by Django 3.2.6 on 2021-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0014_auto_20211004_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='address_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='address_sv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
