# Generated by Django 3.2.6 on 2021-10-15 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0016_auto_20211005_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitGroup',
            new_name='MobileUnitGroup',
        ),
        migrations.CreateModel(
            name='MobileUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('name_fi', models.CharField(max_length=64, null=True)),
                ('name_sv', models.CharField(max_length=64, null=True)),
                ('name_en', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3067)),
                ('address', models.CharField(max_length=100, null=True)),
                ('address_fi', models.CharField(max_length=100, null=True)),
                ('address_sv', models.CharField(max_length=100, null=True)),
                ('address_en', models.CharField(max_length=100, null=True)),
                ('unit_id', models.IntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='data_view.contenttypes')),
                ('unit_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='data_view.mobileunitgroup')),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='chargingstationcontent',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_station_content', to='data_view.mobileunit'),
        ),
        migrations.AlterField(
            model_name='gasfillingstationcontent',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gas_filling_station_content', to='data_view.mobileunit'),
        ),
        migrations.AlterField(
            model_name='statuecontent',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statue_content', to='data_view.mobileunit'),
        ),
        migrations.AlterField(
            model_name='walkingroutecontent',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walking_route_content', to='data_view.mobileunit'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
