# Generated by Django 3.2.6 on 2021-09-21 10:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasStationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('lng_cng', models.CharField(max_length=10, null=True)),
                ('operator', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineStringGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MultiPolygonGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PointGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('geometry_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'CHARING_STATION'), (1, 'GAS_STATION'), (2, 'ROUTE'), (3, 'PARKING_AREA')], null=True)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_ct', models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'charginstationcontent'), ('model', 'gasstationcontent'), ('model', 'routecontent'), ('model', 'parkingareacontent'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_unit', related_query_name='content_obj', to='contenttypes.contenttype')),
                ('geometry_ct', models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeometry'), ('model', 'multipolygongeometry'), ('model', 'polygongeometry'), ('model', 'linestringgeometry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometry_unit', related_query_name='geom_obj', to='contenttypes.contenttype')),
            ],
        ),
    ]
