# Generated by Django 3.2.6 on 2021-09-23 08:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineStringGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MultiPolygonGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('CS', 'ChargingStation'), ('GS', 'GasStation')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygon_geometries', to='mockup.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PointGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_geometries', to='mockup.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='mockup.unit')),
            ],
        ),
        migrations.CreateModel(
            name='GasStationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('lng_cng', models.CharField(max_length=10, null=True)),
                ('operator', models.CharField(max_length=30, null=True)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gas_station_content', to='mockup.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargingStationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('charger_type', models.CharField(max_length=30, null=True)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_station_content', to='mockup.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
