# Generated by Django 3.2.6 on 2021-09-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='mockup.unit'),
        ),
    ]
