# Generated by Django 3.2.6 on 2021-09-17 10:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineStringGeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PointGeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonGeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='geom_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeom'), ('model', 'polygongeom'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geom', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='unit',
            name='geom_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
