# Generated by Django 3.2.6 on 2021-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstationcontent',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chargingstationcontent',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chargingstationcontent',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
