# Generated by Django 3.2.6 on 2021-09-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0002_auto_20210921_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='content_ct',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='geometry_ct',
            new_name='geometry_type',
        ),
    ]
