# Generated by Django 3.2.6 on 2021-09-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0002_auto_20210917_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='geom_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeom'), ('model', 'polygongeom'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='contenttypes.contenttype'),
        ),
    ]
