# Generated by Django 3.2.6 on 2021-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0003_rename_gasstationcontent_gasfillingstationcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='content_type',
            field=models.CharField(choices=[('CS', 'ChargingStation'), ('GFS', 'GasFillingStation')], max_length=3, null=True),
        ),
    ]
