# Generated by Django 3.2.6 on 2021-09-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0004_alter_unit_geom_ct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineStringGeom',
        ),
    ]
