# Generated by Django 3.2.6 on 2021-09-24 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0005_alter_gasfillingstationcontent_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineStringGeometry',
        ),
        migrations.DeleteModel(
            name='MultiPolygonGeometry',
        ),
        migrations.RemoveField(
            model_name='polygongeometry',
            name='unit',
        ),
        migrations.AlterField(
            model_name='geometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3879),
        ),
        migrations.DeleteModel(
            name='PointGeometry',
        ),
        migrations.DeleteModel(
            name='PolygonGeometry',
        ),
    ]
