# Generated by Django 3.2.6 on 2021-09-24 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0006_auto_20210924_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
