# Generated by Django 3.2.6 on 2021-09-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0006_auto_20210920_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='geom_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeom'), ('model', 'multipolygongeom'), ('model', 'polygongeom'), ('model', 'linestringgeom'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='geom_obj', to='contenttypes.contenttype'),
        ),
    ]
