# Generated by Django 3.2.6 on 2021-09-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0007_auto_20210920_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'charginstation'), ('model', 'gasstation'), ('model', 'route'), ('model', 'parkingarea'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='content_obj', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='geom_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeom'), ('model', 'multipolygongeom'), ('model', 'polygongeom'), ('model', 'linestringgeom'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', related_query_name='geom_obj', to='contenttypes.contenttype'),
        ),
    ]
