# Generated by Django 3.2.6 on 2021-09-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0007_alter_unit_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='content_id',
            new_name='object_id',
        ),
    ]
