# Generated by Django 3.2.6 on 2021-09-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0008_rename_content_id_unit_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='object_id',
            new_name='content_id',
        ),
    ]
