# Generated by Django 3.2.6 on 2021-09-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0008_auto_20210920_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharginStation',
            new_name='CharginStationContent',
        ),
        migrations.RenameModel(
            old_name='GasStation',
            new_name='GasStationContent',
        ),
        migrations.RenameModel(
            old_name='LineStringGeom',
            new_name='LineStringGeometry',
        ),
        migrations.RenameModel(
            old_name='MultiPolygonGeom',
            new_name='MultiPolygonGeometry',
        ),
        migrations.RenameModel(
            old_name='ParkingArea',
            new_name='ParkingAreaContent',
        ),
        migrations.RenameModel(
            old_name='PointGeom',
            new_name='PointGeometry',
        ),
        migrations.RenameModel(
            old_name='PolygonGeom',
            new_name='PolygonGeometry',
        ),
        migrations.RenameModel(
            old_name='Route',
            new_name='RouteContent',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='geom_id',
            new_name='geometry_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='geom_ct',
        ),
        migrations.AddField(
            model_name='unit',
            name='geometry_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'pointgeometry'), ('model', 'multipolygongeometry'), ('model', 'polygongeometry'), ('model', 'linestringgeometry'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', related_query_name='geom_obj', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='content_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'charginstationcontent'), ('model', 'gasstationcontent'), ('model', 'routecontent'), ('model', 'parkingareacontent'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='content_obj', to='contenttypes.contenttype'),
        ),
    ]
