# Generated by Django 3.2.6 on 2021-09-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0009_alter_geometry_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='content_type',
            field=models.CharField(choices=[('CGS', 'ChargingStation'), ('CFS', 'GasFillingStation')], max_length=3, null=True),
        ),
    ]
