# Generated by Django 3.2.6 on 2021-09-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0010_rename_content_id_unit_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
