# Generated by Django 3.2.6 on 2021-09-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0010_alter_unit_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(choices=[('CGS', 'ChargingStation'), ('GFS', 'GasFillingStation')], max_length=3, null=True)),
                ('class_name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='content_type',
        ),
        migrations.AddField(
            model_name='unit',
            name='contet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='units', to='mockup.contenttype'),
        ),
    ]
