# Generated by Django 3.2.6 on 2021-09-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0011_remove_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='object_id',
            new_name='content_id',
        ),
    ]
