# Generated by Django 3.2.6 on 2021-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0012_alter_unit_contet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
