# Generated by Django 3.2.6 on 2021-09-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0013_contenttype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='contet_type',
            new_name='content_type',
        ),
    ]
