# Generated by Django 3.2.6 on 2021-09-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0015_auto_20210928_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='content_type_short_name',
            new_name='content_type_name',
        ),
    ]
