# Generated by Django 3.2.6 on 2021-09-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mockup', '0016_rename_content_type_short_name_unit_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(choices=[('CGS', 'ChargingStation'), ('GFS', 'GasFillingStation')], max_length=3, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('class_name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='content_type_name',
        ),
        migrations.AlterField(
            model_name='unit',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='contenttypes.contenttype'),
        ),
    ]
