# Generated by Django 3.2.6 on 2021-09-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0017_auto_20210928_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mockup.contenttypes'),
        ),
    ]
