# Generated by Django 3.2.5 on 2021-08-25 09:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='week',
            new_name='week_number',
        ),
        migrations.RemoveField(
            model_name='week',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='eco_counter.month'),
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='eco_counter.week'),
        ),
        migrations.AddField(
            model_name='month',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='eco_counter.location'),
        ),
        migrations.AddField(
            model_name='month',
            name='month_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021),
        ),
        migrations.AddField(
            model_name='week',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='eco_counter.month'),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021),
        ),
        migrations.AddField(
            model_name='weekday',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_day', to='eco_counter.week'),
        ),
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_ak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_ap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_jk',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_jp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_jt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_pk',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_pp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='day',
            name='values_pt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
