# Generated by Django 3.2.5 on 2021-08-24 07:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_imported', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1)),
                ('values_ak', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_ap', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_at', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_pk', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_pp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_pt', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_jk', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_jp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('values_jt', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='eco_counter.location')),
            ],
        ),
    ]
