# Generated by Django 3.2.5 on 2021-08-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0004_weekday_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='month',
        ),
        migrations.AlterField(
            model_name='weekday',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='eco_counter.week'),
        ),
    ]
