# Generated by Django 3.2.5 on 2021-08-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0005_auto_20210826_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_ak', models.PositiveSmallIntegerField(null=True)),
                ('values_ap', models.PositiveSmallIntegerField(null=True)),
                ('values_at', models.PositiveSmallIntegerField(null=True)),
                ('values_pk', models.PositiveSmallIntegerField(null=True)),
                ('values_pp', models.PositiveSmallIntegerField(null=True)),
                ('values_pt', models.PositiveSmallIntegerField(null=True)),
                ('values_jk', models.PositiveSmallIntegerField(null=True)),
                ('values_jp', models.PositiveSmallIntegerField(null=True)),
                ('values_jt', models.PositiveSmallIntegerField(null=True)),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_data', to='eco_counter.year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_ak', models.PositiveSmallIntegerField(null=True)),
                ('values_ap', models.PositiveSmallIntegerField(null=True)),
                ('values_at', models.PositiveSmallIntegerField(null=True)),
                ('values_pk', models.PositiveSmallIntegerField(null=True)),
                ('values_pp', models.PositiveSmallIntegerField(null=True)),
                ('values_pt', models.PositiveSmallIntegerField(null=True)),
                ('values_jk', models.PositiveSmallIntegerField(null=True)),
                ('values_jp', models.PositiveSmallIntegerField(null=True)),
                ('values_jt', models.PositiveSmallIntegerField(null=True)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_data', to='eco_counter.week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_ak', models.PositiveSmallIntegerField(null=True)),
                ('values_ap', models.PositiveSmallIntegerField(null=True)),
                ('values_at', models.PositiveSmallIntegerField(null=True)),
                ('values_pk', models.PositiveSmallIntegerField(null=True)),
                ('values_pp', models.PositiveSmallIntegerField(null=True)),
                ('values_pt', models.PositiveSmallIntegerField(null=True)),
                ('values_jk', models.PositiveSmallIntegerField(null=True)),
                ('values_jp', models.PositiveSmallIntegerField(null=True)),
                ('values_jt', models.PositiveSmallIntegerField(null=True)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_data', to='eco_counter.month')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
