# Generated by Django 3.2.5 on 2021-08-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0009_auto_20210826_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdata',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_data', to='eco_counter.location'),
        ),
    ]
