# Generated by Django 3.2.5 on 2021-08-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0011_auto_20210826_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdata',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_data', to='eco_counter.month'),
        ),
    ]
