# Generated by Django 3.2.5 on 2021-08-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0012_weekdata_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthdata',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_data', to='eco_counter.location'),
        ),
        migrations.AddField(
            model_name='yeardata',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_data', to='eco_counter.location'),
        ),
    ]
