# Generated by Django 3.2.5 on 2021-08-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0013_auto_20210826_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthdata',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_data', to='eco_counter.year'),
        ),
    ]
