# Generated by Django 3.2.5 on 2021-08-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0014_monthdata_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year_number',
        ),
    ]
