# Generated by Django 3.2.5 on 2021-08-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0015_rename_year_year_year_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='eco_counter.location'),
        ),
    ]
