# Generated by Django 3.2.5 on 2021-08-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0016_year_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
        migrations.AddField(
            model_name='week',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='eco_counter.month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='eco_counter.year'),
        ),
    ]
