# Generated by Django 3.2.5 on 2021-08-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0017_auto_20210827_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importstate',
            old_name='year',
            new_name='year_number',
        ),
    ]
