# Generated by Django 3.2.5 on 2021-08-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0018_rename_year_importstate_year_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='eco_counter.year'),
        ),
    ]
