# Generated by Django 3.2.5 on 2021-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0019_week_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstate',
            name='year_number',
            field=models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021)], default=2020),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_number',
            field=models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021)], default=2021),
        ),
    ]
