# Generated by Django 3.2.5 on 2021-08-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0021_auto_20210830_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importstate',
            name='week_number',
        ),
    ]
