# Generated by Django 3.2.5 on 2021-08-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0022_remove_importstate_week_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importstate',
            old_name='month_number',
            new_name='current_month_number',
        ),
        migrations.RenameField(
            model_name='importstate',
            old_name='year_number',
            new_name='current_year_number',
        ),
    ]
