# Generated by Django 3.2.5 on 2021-08-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0023_auto_20210830_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Station',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='monthdata',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='weekdata',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='weekday',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='location',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='yeardata',
            old_name='location',
            new_name='station',
        ),
    ]
