# Generated by Django 3.2.5 on 2021-09-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0025_importstate_current_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='month',
        ),
        migrations.RemoveField(
            model_name='weekdata',
            name='month',
        ),
    ]
