# Generated by Django 3.2.5 on 2021-09-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0030_remove_importstate_current_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='station',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_ak',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_ap',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_at',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_jk',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_jp',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_jt',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_pk',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_pp',
        ),
        migrations.RemoveField(
            model_name='day',
            name='value_pt',
        ),
        migrations.RemoveField(
            model_name='hourdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hourdata',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='hourdata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='hourdata',
            name='week',
        ),
        migrations.AddField(
            model_name='hourdata',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_data', to='eco_counter.day'),
        ),
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ak', models.PositiveIntegerField(default=0)),
                ('value_ap', models.PositiveIntegerField(default=0)),
                ('value_at', models.PositiveIntegerField(default=0)),
                ('value_pk', models.PositiveIntegerField(default=0)),
                ('value_pp', models.PositiveIntegerField(default=0)),
                ('value_pt', models.PositiveIntegerField(default=0)),
                ('value_jk', models.PositiveIntegerField(default=0)),
                ('value_jp', models.PositiveIntegerField(default=0)),
                ('value_jt', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_data', to='eco_counter.day')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_data', to='eco_counter.station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
