# Generated by Django 3.2.5 on 2021-09-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0031_auto_20210904_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='eco_counter.year'),
        ),
    ]
