# Generated by Django 3.2.5 on 2021-09-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0032_day_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='eco_counter.station'),
        ),
    ]
