# Generated by Django 3.2.5 on 2021-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0033_day_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='daydata',
            options={'ordering': ['-day__date']},
        ),
        migrations.AlterModelOptions(
            name='hourdata',
            options={'ordering': ['-day__date']},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['-year__year_number', '-month_number']},
        ),
        migrations.AlterModelOptions(
            name='monthdata',
            options={'ordering': ['-year__year_number', '-month__month_number']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-year__year_number', '-week_number']},
        ),
        migrations.AlterModelOptions(
            name='weekdata',
            options={'ordering': ['-week__year__year_number', '-week__week_number']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year_number']},
        ),
        migrations.AlterModelOptions(
            name='yeardata',
            options={'ordering': ['-year__year_number']},
        ),
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ManyToManyField(to='eco_counter.Year'),
        ),
    ]
