# Generated by Django 3.2.5 on 2021-09-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_counter', '0034_auto_20210908_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weekdata',
            options={},
        ),
        migrations.RenameField(
            model_name='week',
            old_name='year',
            new_name='years',
        ),
    ]
